INFO:root:server: gác xép nh\u1ecf c\u1ee7a hoàng t\u1eed, user: bot.nosense, nick: vux
INFO:root:server: gác xép nh\u1ecf c\u1ee7a hoàng t\u1eed, user: maybe#0142, nick: None
ERROR:discord.client:Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\BOT Nosense\_projects\carot.vn\bot_discord\environment\dev\venv\Lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\BOT Nosense\_projects\carot.vn\bot_discord\app.py", line 25, in on_message
    logging.info(f'server: {message.guild}, user: {message.author}, nick: {message.author.nick}')
                                                                          ^^^^^^^^^^^^^^^^^^^
AttributeError: 'User' object has no attribute 'nick'
DEBUG:asyncio:Using proactor: IocpProactor
INFO:discord.client:logging in using static token
INFO:discord.gateway:Shard ID None has connected to Gateway (Session ID: fce4c8fd636402ac630c99574a024433).
INFO:root:We have logged in as maybe#0142
INFO:root:server: None, user: bot.nosense
INFO:root:server: None, user: maybe#0142
INFO:root:server: None, user: maybe#0142
INFO:root:server: gác xép nh\u1ecf c\u1ee7a hoàng t\u1eed, user: bot.nosense
INFO:root:server: gác xép nh\u1ecf c\u1ee7a hoàng t\u1eed, user: maybe#0142
DEBUG:asyncio:Using proactor: IocpProactor
INFO:discord.client:logging in using static token
INFO:discord.gateway:Shard ID None has connected to Gateway (Session ID: 61ef3fac1ff97ef9b915ab9fa2e51b55).
INFO:root:server: gác xép nh\u1ecf c\u1ee7a hoàng t\u1eed, user: bot.nosense
INFO:root:server: gác xép nh\u1ecf c\u1ee7a hoàng t\u1eed, user: maybe#0142
INFO:root:We have logged in as maybe#0142
DEBUG:asyncio:Using proactor: IocpProactor
INFO:discord.client:logging in using static token
